### ISSUE TITLE
Uncertainty on which media_type audio sub flows using the AAC codec should use

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/bcp-nmos-ndi#4]
Currently the specs recommend using [audio/mpeg4-generic](https://www.iana.org/assignments/media-types/audio/mpeg4-generic)
https://github.com/AMWA-TV/bcp-007-01/blob/036660a98dca3912645ccdfb5c2c3f2d486a90cb/docs/Overview.md?plain=1#L230

However we've also identified [audio/aac](https://www.iana.org/assignments/media-types/audio/aac) as an IANA registered type.

**Comment by pedro-alves-ferreira** [comment]
I had never seen `audio/mpeg4-generic`. On a quick look at https://www.iana.org/assignments/media-types/audio/mpeg4-generic, what strikes me as odd is:

```
Restrictions on usage:

   Only defined for real-time transfers of audio/mpeg4-generic RTP streams with mode=rtp-midi.
```

What is the reason not to use `audio/aac`?

**Comment by garethsb** [comment]
Good question...

The trouble is that IANA media type register is (mostly?) used for RTP payload formats... whereas in a Flow we are trying to be transport-agnostic, as format/codec identification.

The registration for `audio/aac` seems to be used for a file/stream format, not an RTP payload format, and doesn't identify a defining spec e.g. IETF RFC. It's surprisingly recent, 2018.

Looks to me like the original info in the register for `audio/mpeg4-generic` may have been stomped on when `mode=rtp-midi` was added by RFC 6295. The original spec and registration of media type for MPEG-4 AAC is [RFC 3640](https://datatracker.ietf.org/doc/html/rfc3640#section-4.1).

**Comment by alabou** [comment]
When AAC audio is to be transported over RTP using RFC 3640 or RFC 6416 the media type is required to be audio/mpeg4-generic or  audio/MP4A-LATM respectively.

By extension when the AAC audio is transported in MPEG2-TS the media type should be audio/MP4A-ADTS which is new and has to be registered at IANA

The objective of such media types is to describe as precisely as possible the AAC stream. The audio/aac media type is not associated to any RFC (not for RTP) and let the stream be LATM or ADTS only and be discovered at run time.

I think that for the NDI mux we should use the most "generic" name for the flow, hence audio/mpeg4-generic, and let the NDI subsystem rules prevail about how to transport it.
